name: Atualização do banco de dados

# on:
#   schedule:
#     - cron: "0 12 * * *" # Executar diariamente às 12h

on: push

jobs:
  atualizacao_nba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configuração do ambiente
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Update-ca-certificates
        run: sudo update-ca-certificates

      - name: Instalação de dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Execução do script Python
        run: python scripts/update-db.py
        env:
          HOST: ${{ secrets.HOST }}
          DATABASE: ${{ secrets.DATABASE }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SSL_MODE: ${{ secrets.SSL_MODE }}
          SSL_CERT: ${{ secrets.SSL_CERT }}
