name: Atualização de dados NBA

on:
  schedule:
    - cron: "0 12 * * *" # Executar diariamente às 12h

jobs:
  atualizacao_nba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configuração do ambiente
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Instalação de dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements-update-database.txt

      - name: Execução do script Python
        run: python scripts/update-database.py
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
